// Bana's spoken location intros — bilingual, paged one line at a time.
// Keyed by route:  explorer:<level>  |  mission:<missionId>
export const INTROS = {
  'explorer:1': { en: ["This is Baglung — a green hill town wrapped in forest and terraced farms.", "Walk around and make the greener choice at each spot to keep the valley healthy."], ne: ["यो बागलुङ हो — वन र खेतले घेरिएको हरियो पहाडी सहर।", "घुम्दै हरेक ठाउँमा हरित विकल्प छानेर उपत्यका स्वस्थ राख्नुहोस्।"] },
  'explorer:2': { en: ["Welcome to Chitwan — warm Terai farmland right beside the jungle.", "Explore and choose what keeps the soil, air and wildlife healthy."], ne: ["चितवनमा स्वागत छ — जङ्गल छेउको न्यानो तराई खेतीयोग्य भूमि।", "घुम्दै माटो, हावा र वन्यजन्तु स्वस्थ राख्ने कुरा छान्नुहोस्।"] },
  'explorer:3': { en: ["This is Kathmandu — our busy capital, full of traffic and old temples.", "Find the low-carbon choice at each corner to clear the city's air."], ne: ["यो काठमाडौं हो — ट्राफिक र पुराना मन्दिरले भरिएको हाम्रो व्यस्त राजधानी।", "सहरको हावा सफा गर्न हरेक कुनामा कम-कार्बन विकल्प खोज्नुहोस्।"] },
  'explorer:4': { en: ["The Kali Gandaki gorge — a deep river valley carved between the hills.", "Roam and protect the river and slopes with smart choices."], ne: ["कालीगण्डकी घाटी — पहाडबीच कोरिएको गहिरो नदी उपत्यका।", "घुम्दै बुद्धिमानी छनोटले नदी र भिरालो जोगाउनुहोस्।"] },
  'explorer:5': { en: ["You're high in the Himalaya now — glaciers, thin air and fragile trails.", "Every choice matters up here; keep the mountains clean."], ne: ["तपाईं अहिले उच्च हिमालमा हुनुहुन्छ — हिमनदी, पातलो हावा र नाजुक बाटा।", "यहाँ हरेक छनोट महत्त्वपूर्ण छ; हिमाल सफा राख्नुहोस्।"] },
  'explorer:6': { en: ["Dhulikhel — a calm hill station with mountain views and old Newari streets.", "Explore and pick the choices that keep its air crisp."], ne: ["धुलिखेल — हिमाल देखिने शान्त पहाडी सहर र पुराना नेवारी गल्ली।", "घुम्दै हावा ताजा राख्ने छनोट गर्नुहोस्।"] },
  'explorer:7': { en: ["Janakpur — the Mithila city of the Janaki temple and sacred ponds.", "Walk the town and choose what protects its water and heritage."], ne: ["जनकपुर — जानकी मन्दिर र पवित्र पोखरीको मिथिला सहर।", "सहर घुम्दै पानी र सम्पदा जोगाउने छनोट गर्नुहोस्।"] },
  'explorer:8': { en: ["Lumbini — the peaceful birthplace of the Buddha.", "Explore the gardens and make choices worthy of this sacred place."], ne: ["लुम्बिनी — बुद्धको शान्त जन्मस्थल।", "बगैंचा घुम्दै यस पवित्र ठाउँअनुरूप छनोट गर्नुहोस्।"] },
  'explorer:9': { en: ["Shuklaphanta — far-west grassland and sal forest, full of wildlife.", "Roam and protect the grassland, the wetland and the animals."], ne: ["शुक्लाफाँटा — वन्यजन्तुले भरिएको सुदूरपश्चिम घाँसे मैदान र सालको वन।", "घुम्दै घाँसे मैदान, सिमसार र जनावर जोगाउनुहोस्।"] },

  'mission:m1': { en: ["Butwal, morning rush — you need to get across town to school.", "Choose how you travel: keep it cheap on carbon and dodge the traffic!"], ne: ["बुटवल, बिहानको भीड — सहरपारि विद्यालय पुग्नुपर्छ।", "कसरी यात्रा गर्ने छान्नुहोस्: कार्बन कम राख्नुहोस् र ट्राफिक छल्नुहोस्!"] },
  'mission:m_dd': { en: ["Dadeldhura — a steep far-west hill town. The school run is tough here.", "Pick a clean way to travel and make it through the winding hill road."], ne: ["डँडेल्धुरा — उकालो सुदूरपश्चिम पहाडी सहर। यहाँ विद्यालय जाने बाटो कठिन छ।", "सफा यात्रा छानेर घुमाउरो पहाडी बाटो पार गर्नुहोस्।"] },
  'mission:m2': { en: ["Tansen's school has lights and fans left on in every room.", "Patrol the rooms and switch off whatever is wasting power."], ne: ["तानसेनको विद्यालयका हरेक कोठामा बत्ती र पंखा बलिरहेका छन्।", "कोठा घुमेर बिजुली खेर फाल्ने कुरा बन्द गर्नुहोस्।"] },
  'mission:cook': { en: ["A Gorkha kitchen — how you cook decides how much smoke and CO₂ you make.", "Choose the cleaner stove and fuel for the meal."], ne: ["गोरखाको भान्सा — कसरी पकाउनुहुन्छ भन्नेले धुवाँ र CO₂ निर्धारण गर्छ।", "खानाका लागि सफा चुलो र इन्धन छान्नुहोस्।"] },
  'mission:m3': { en: ["Phewa Lake in Pokhara is choking with plastic and waste.", "Clean the lake and sort out everything you pull from the water."], ne: ["पोखराको फेवा ताल प्लास्टिक र फोहोरले भरिएको छ।", "ताल सफा गरेर पानीबाट निकालेको सबै कुरा छुट्याउनुहोस्।"] },
  'mission:m6': { en: ["Monsoon in Dhangadhi — the drains are clogging and the water is rising fast.", "Clear the drains and keep the town from flooding!"], ne: ["धनगढीमा मनसुन — ढल बन्द हुँदै र पानी छिटो बढ्दै।", "ढल सफा गरेर सहरलाई डुब्नबाट जोगाउनुहोस्!"] },
  'mission:m5': { en: ["Api Himal base camp — trekkers have left litter all over the snow.", "Carry the rubbish back to the collection point and keep the mountain clean."], ne: ["आपी हिमाल आधार शिविर — पदयात्रीले हिउँभरि फोहोर छाडेका छन्।", "फोहोर सङ्कलन केन्द्रसम्म लैजानुहोस् र हिमाल सफा राख्नुहोस्।"] },
  'mission:m8': { en: ["A Panchkhal market — waste is piling up, all mixed together.", "Sort each item into compost, recycling or landfill before time runs out."], ne: ["पाँचखाल बजार — फोहोर मिसिएर थुप्रिँदै।", "समय सकिनुअघि हरेक कुरा कम्पोस्ट, पुनःचक्रण वा ल्यान्डफिलमा छुट्याउनुहोस्।"] },
  'mission:jungle': { en: ["Bardiya\u2019s sal forest \u2014 home to rhinos, elephants and tigers, and a giant store of carbon.", "Spot the wildlife, put out the poachers\u2019 fire and plant new trees as you patrol."], ne: ["\u092c\u0930\u094d\u0926\u093f\u092f\u093e\u0915\u094b \u0938\u093e\u0932\u0935\u0928 \u2014 \u0917\u0948\u0901\u0921\u093e, \u0939\u093e\u0924\u094d\u0924\u0940 \u0930 \u092c\u093e\u0918\u0915\u094b \u0918\u0930\u0964", "\u0917\u0938\u094d\u0924\u0940 \u0917\u0930\u094d\u0926\u0948 \u0935\u0928\u094d\u092f\u091c\u0928\u094d\u0924\u0941 \u0926\u0947\u0916\u094d\u0928\u0941\u0939\u094b\u0938\u094d, \u0938\u093f\u0915\u093e\u0930\u0940\u0915\u094b \u0906\u0917\u094b \u0928\u093f\u092d\u093e\u0909\u0928\u0941\u0939\u094b\u0938\u094d \u0930 \u0928\u092f\u093e\u0901 \u0930\u0941\u0916 \u0930\u094b\u092a\u094d\u0928\u0941\u0939\u094b\u0938\u094d\u0964"] },
};
